version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # RabbitMQ management UI
    networks:
      - smart-campus-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5

  api-gateway: # Add the new api-gateway service
    build:
      context: ./app/api-gateway
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8000:8000" # Map host port 8009 to container port 8000 (assuming internal port is 8000)
    depends_on:
      - rabbitmq # Depend on rabbitmq
      # You might also want to add dependencies on other services the gateway routes to
    networks:
      - smart-campus-network

  login-service: # Added login service
    build:
      context: ./app/login-service
    environment:
      - RABBITMQ_HOST=rabbitmq
      - SUPABASE_URL=${SUPABASE_URL4}
      - SUPABASE_KEY=${SUPABASE_KEY4}
      - SECRET_KEY=${SECRET_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    ports:
      - "8100:8000" # Using port 8009 for the login service
    depends_on:
      - rabbitmq
    networks:
      - smart-campus-network

  vehicle-detector:
    build:
      context: ./app/vehicle-detector
    environment:
      - RABBITMQ_HOST=rabbitmq
      - SUPABASE_URL=${SUPABASE_URL3}
      - SUPABASE_KEY=${SUPABASE_KEY3}
    ports:
      - "8001:8000"
    depends_on:
      - rabbitmq
    networks:
      - smart-campus-network

  authorization-service:
    build:
      context: ./app/authorization-service
    environment:
      - RABBITMQ_HOST=rabbitmq
      - SUPABASE_URL=${SUPABASE_URL3}
      - SUPABASE_KEY=${SUPABASE_KEY3}
    ports:
      - "8002:8000"
    depends_on:
      - rabbitmq
    networks:
      - smart-campus-network

  logger-service:
    build:
      context: ./app/logger-service
    environment:
      - RABBITMQ_HOST=rabbitmq
      - SUPABASE_URL=${SUPABASE_URL3}
      - SUPABASE_KEY=${SUPABASE_KEY3}
    ports:
      - "8003:8000"
    depends_on:
      - rabbitmq
    networks:
      - smart-campus-network

  security-dashboard-service:
    build:
      context: ./app/security-dashboard-service
    environment:
      - RABBITMQ_HOST=rabbitmq
      - SUPABASE_URL=${SUPABASE_URL3}
      - SUPABASE_KEY=${SUPABASE_KEY3}
    ports:
      - "8004:8000"
    depends_on:
      - rabbitmq
    networks:
      - smart-campus-network

  course-enrollment:
    build:
      context: ./app/course-enrollment
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8005:8000"
    depends_on:
      - rabbitmq
    networks:
      - smart-campus-network

  notifications-service: # Add the new notifications service
    build:
      context: ./app/notifications
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8007:8000" # Map host port 8007 to container port 8000
    depends_on:
      rabbitmq:
        condition: service_healthy # Add this line

    networks:
      - smart-campus-network

  attendance-service: # Add the new attendance service
    build:
      context: ./app/attendance
    environment:
      - RABBITMQ_HOST=rabbitmq
      - SUPABASE_URL=${SUPABASE_URL1}
      - SUPABASE_KEY=${SUPABASE_KEY1}
    ports:
      - "8006:8000" # Map host port 8006 to container port 4000
    depends_on:
      - rabbitmq
    networks:
      - smart-campus-network

  schedule-manager: # Add the new schedule-manager service
    build:
      context: ./app/schedule-manager
    environment:
      - RABBITMQ_HOST=rabbitmq
      - SUPABASE_URL=${SUPABASE_URL1}
      - SUPABASE_KEY=${SUPABASE_KEY1}
    ports:
      - "8008:8000" # Map host port 8008 to container port 8000
    depends_on:
      - rabbitmq # Depends on rabbitmq
    networks:
      - smart-campus-network

  resource-management: # Add the new resource-management service
    build:
      context: ./app/resource-management
    environment:
      - RABBITMQ_HOST=rabbitmq # Include RabbitMQ host if needed
    ports:
      - "8010:8000" # Map host port 8010 to container port 8000
    depends_on:
      - rabbitmq # Depends on rabbitmq
    networks:
      - smart-campus-network

  chatbot-backend: # Add the new chatbot service
    build:
      context: ./app/chatbot/backend
    environment:
      - RABBITMQ_HOST=rabbitmq
      - SUPABASE_URL=${SUPABASE_URL1}
      - SUPABASE_KEY=${SUPABASE_KEY1}
      - DB_HOST=${DB_HOST1}
      - DB_PORT=${DB_PORT1}
      - DB_USER=${DB_USER1}
      - DB_PASSWORD=${DB_PASSWORD1}
      - DB_DATABASE=${DB_DATABASE1}
    ports:
      - "8012:8000" # Map host port 8011 to container port 8000
    depends_on:
      - rabbitmq # Depends on rabbitmq
    networks:
      - smart-campus-network

  chatbot-actions: # Add the new chatbot service
    build:
      context: ./app/chatbot/campus_chatbot/actions
    environment:
      - RABBITMQ_HOST=rabbitmq
      - SUPABASE_URL=${SUPABASE_URL1}
      - SUPABASE_KEY=${SUPABASE_KEY1}
      - SCHEDULER_BASE_URL=${SCHEDULER_BASE_URL1}
    ports:
      - "8014:8000" # Map host port 8012 to container port 8000
    depends_on:
      - rabbitmq # Depends on rabbitmq
    networks:
      - smart-campus-network

  chatbot-service: # Add the new chatbot service
    build:
      context: ./app/chatbot/campus_chatbot
    environment:
      - RABBITMQ_HOST=rabbitmq
      - SUPABASE_URL=${SUPABASE_URL1}
      - SUPABASE_KEY=${SUPABASE_KEY1}
    ports:
      - "8016:8000" # Map host port 8013 to container port 8000
    depends_on:
      - rabbitmq # Depends on rabbitmq
    networks:
      - smart-campus-network

networks:
  smart-campus-network:
    driver: bridge
